In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4])

print("shape a:{}".format(a.shape))    # Shape of the array
print("ndim {}".format(a.ndim))        # Number of dimensions
print("size {}".format(a.size))         # Total number of elements
print(f"dtype {a.dtype}")              # Data type of the elements
print(f"itemsize {a.itemsize}")        # Size of each element in bytes
print(f"data {a.data}")                # Buffer containing the actual elements


shape a:(5,)
ndim 1
size 5
dtype int64
itemsize 8
data <memory at 0x7fc853455640>


In [3]:
a1=np.array([[2,3,4,5],
             [1,4,7,6]])
a2=np.array([[1,1,1],[1,1,1]])
#add(), subtract(),mod(),reminder(),multiply(),divide(), power(),absolute()#
#Slicing
#slicing operation a1[:2, :2] is used to create sliced_arr, 
#which contains a subset of the original array a1.

sliced_arr=a1[:2,:2]
print(sliced_arr)

[[2 3]
 [1 4]]


In [4]:
index_arr=a1[[1,1],[2,1]]

#The print() function is used to display the contents of index_arr.
print(index_arr)


[7 4]


In [5]:
#method of the NumPy array is used to 
#calculate the sum of all elements

print(a1.sum())

32


In [6]:
#NumPy array is used to calculate the sum of all elements.

arr=np.array([[25,64],[89,36]])
print(arr.sum())

214


In [7]:
#to compute the square root of each element in the array.

print(np.sqrt(arr))

[[5.         8.        ]
 [9.43398113 6.        ]]


In [8]:
#to obtain the transpose of the array.

print(arr.T)

[[25 89]
 [64 36]]


In [9]:
#to perform matrix multiplication
#of b1 and b2

b1=np.array([[2,3],[4,5]])
b2=np.array([[5,6],[7,8]])
matrix_multi=np.dot(b1,b2)
print(matrix_multi)

[[31 36]
 [55 64]]


In [10]:
#np.all(): Checks if all elements are True.
#np.any(): (if included) Checks if any elements are True.

bool=np.array([[True,True],[False,True]])
print("all() with axis none",np.all(bool))
print("all() with axis 0",np.all(bool,axis=0))#any()

all() with axis none False
all() with axis 0 [False  True]


In [11]:
#to display the contents of the variables temp and re.

temp=np.arange(9)
print(temp)
re=temp.reshape(3,3)
print(re)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#o extract specific elements from the array 
#re along the specified axis.

print(np.take(re,[0,1],axis=1))

[[0 1]
 [3 4]
 [6 7]]


In [13]:
x=np.array([[12,23],[23,34]])
y=np.array([[56,67],[78,89]])
z=np.array([[32,43],[54,65]])
v=np.vstack((x,y,z))
h=np.hstack((x,y,z))

#Used for vertical stacking of arrays.
print("vstack:",v)
#Used for horizontal stacking of arrays.
print("hstack:",h)

vstack: [[12 23]
 [23 34]
 [56 67]
 [78 89]
 [32 43]
 [54 65]]
hstack: [[12 23 56 67 32 43]
 [23 34 78 89 54 65]]


In [14]:
h_split=np.hsplit(h,3)
print("split:",split)
v_split=np.vsplit(h,2)
print("vsplit:",v_split)

NameError: name 'split' is not defined

In [15]:
h_split = np.hsplit(h, 3)
#Used for horizontal splitting of arrays.
print("h_split:", h_split)
v_split = np.vsplit(h, 2)
#Used for vertical splitting of arrays.
print("v_split:", v_split) 

h_split: [array([[12, 23],
       [23, 34]]), array([[56, 67],
       [78, 89]]), array([[32, 43],
       [54, 65]])]
v_split: [array([[12, 23, 56, 67, 32, 43]]), array([[23, 34, 78, 89, 54, 65]])]


In [16]:
arr=np.array([23,34,45,67])
print("Sqrt: ",np.sqrt(arr))#Returns the square root of each element 
print("Exp: ",np.exp(arr))     #Returns the exponentials of each element
print("Sin: ",np.sin(arr))     #Returns the sin of each element
print("Cos: ",np.cos(arr))     #Returns the cosine of each element
print("Log: ",np.log(arr))     #Returns the logarithm of each element
print("Sum: ",np.sum(arr))     #Returns the sum total of elements in the array
print("Std: ",np.std(arr))     #Returns the standard deviation of in the array

Sqrt:  [4.79583152 5.83095189 6.70820393 8.18535277]
Exp:  [9.74480345e+09 5.83461743e+14 3.49342711e+19 1.25236317e+29]
Sin:  [-0.8462204   0.52908269  0.85090352 -0.85551998]
Cos:  [-0.53283302 -0.84857027  0.52532199 -0.5177698 ]
Log:  [3.13549422 3.52636052 3.80666249 4.20469262]
Sum:  169
Std:  16.269219403523945


In [17]:
#Generates random floats in the range 
print("random: {}\n".format(np.random.random(20)));
#specified shape
print("rand: {}\n".format(np.random.rand(3, 4)));
#integers i
print("randint: {}\n".format(np.random.randint(0, 100, 20)));
#Returns a random permutation of a sequence or array.
print("permutation: {}\n".format(np.random.permutation(np.arange(20))));

random: [0.84897584 0.75692791 0.16576516 0.02596712 0.51043958 0.54582153
 0.64509637 0.26242157 0.15311674 0.3474485  0.59929644 0.76138383
 0.48146201 0.59284682 0.03661602 0.05721527 0.00159504 0.0225325
 0.27230852 0.89220847]

rand: [[0.34944736 0.63226177 0.57713591 0.22699824]
 [0.50501637 0.55002684 0.68779123 0.21180762]
 [0.67862101 0.22177722 0.56005015 0.06528872]]

randint: [58 43 13 27 34 33 54 79 54 95 91 49 59 43 72 44  8 71 25 20]

permutation: [12 11  2 17  7 16  0  4  1  3  8 15  9 13  6  5 19 18 10 14]

